const authenticateUser = async (req, res, next) => {
  try {
  } catch (error) {
    next(error);
  }
};
